name: ci
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.3', '8.4']
        magento: ['2.4.7', '2.4.8']
        coveralls: [ true ]
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '8.3'
            magento: '2.4.7'
            coveralls: false
          - operating-system: 'ubuntu-latest'
            php-versions: '8.3'
            magento: '2.4.8'
            coveralls: false
          - operating-system: 'ubuntu-latest'
            php-versions: '8.4'
            magento: '2.4.8'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          coverage: xdebug
          extensions: bcmath, gd

      - name: Install Composer dependencies
        run: composer install

      - name: Install Magento 2.4.7
        if: matrix.magento == '2.4.7'
        run: |
          composer remove --no-update magento/framework magento/module-backend magento/module-customer magento/module-store magento/module-ui
          composer require magento/framework:103.0.7 magento/module-backend:102.0.7 magento/module-customer:103.0.7 magento/module-store:101.1.7 magento/module-ui:101.2.7

      - name: Install Magento 2.4.8
        if: matrix.magento == '2.4.8'
        run: |
          composer remove --no-update magento/framework magento/module-backend magento/module-customer magento/module-store magento/module-ui
          composer require magento/framework:103.0.8 magento/module-backend:102.0.8 magento/module-customer:103.0.8 magento/module-store:101.1.8 magento/module-ui:101.2.8

      - name: Codesniffer
        run: composer cs-check

      - name: Static code analysis
        if: matrix.coveralls == true
        run: composer analyze

      - name: Unittests
        if: matrix.coveralls == false
        run: composer test

      - name: Unittests with coverage
        if: matrix.coveralls == true
        run: composer coverage

      - name: Coveralls report
        if: matrix.coveralls == true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./vendor/bin/php-coveralls --coverage_clover=clover.xml -v
